name: harrison
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17752077989280224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8125
  lightness: 0.08903975877910852
  saturation: 0.17911232332699
  rhythmicContrast: 0.8592210453934968
purpose: []
